### ISSUE TITLE
Allow to reorder containers

### ISSUE THREAD

**Issue by matkoch** [maciekmm/container-tabs-sidebar#47] opened 2019-10-12 23:25 UTC
Currently, I have to create them in the correct order.

**Comment by maciekmm** [comment] 2019-10-13 10:42
Duplicate of #7 
This is a long planned feature and will be added in the near feature.
As a workaround you can either do what you do or go to firefox/{profile}/containers.json and reorder them there.
There's no official API for doing so, but a custom solution will be implemented.

BTW: Thank You for your donation, I really appreciate it :tada:

**Closed by maciekmm** 2019-10-13 10:42 UTC
